import "./global.css";
import type { Metadata } from "next";
import fonts from "@/fonts";
import GlobalProviders from "@/providers/GlobalProviders";
import { twMerge } from "tailwind-merge";
import { NavBar } from "@/components";

const myFonts = fonts;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body
        className={twMerge(
          myFonts.className,
          "bg-white dark:bg-black px-6 lg:px-[10%] xl:px-[20%] py-6 2xl:py-20 based-text-size"
        )}
      >
        <NavBar />
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
