import "./global.css";
import type { Metadata } from "next";
import fonts from "@/fonts";
import GlobalProviders from "@/providers/GlobalProviders";
import { twMerge } from "tailwind-merge";
import { NavBar } from "@/components";
import ThemeChanger from "@/components/common/theme-changer";

const myFonts = fonts;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="white">
      <body
        className={twMerge(
          myFonts.className,
          "text-black dark:text-white bg-white dark:bg-dark-bg px-6 lg:px-[10%] xl:px-[20%] py-6 2xl:py-20 based-text-size"
        )}
      >
        <GlobalProviders>
          <NavBar />
          <div className="absolute right-[5%] top-[2.5%]">
            <ThemeChanger />
          </div>
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
